#!/usr/bin/env bash
set -euo pipefail

# Issue #41 rerun wrapper: keep the known DeepSeek-V4-Flash SM120-safe attempt
# reproducible while the implementation details stay in the B12x G4 harness.
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

ISSUE_NUMBER="${ISSUE_NUMBER:-41}" \
GCLOUD_ACCOUNT="${GCLOUD_ACCOUNT:-${CLOUDSDK_CORE_ACCOUNT:-}}" \
VLLM_ATTENTION_BACKEND="${VLLM_ATTENTION_BACKEND:-FLASHINFER_MLA_SPARSE_DSV4}" \
VLLM_ENFORCE_EAGER="${VLLM_ENFORCE_EAGER:-1}" \
HYDRALISK_DEEPSEEK_O_PROJ_FALLBACK="${HYDRALISK_DEEPSEEK_O_PROJ_FALLBACK:-bf16_einsum}" \
HYDRALISK_DEEPSEEK_O_PROJ_RECIPE="${HYDRALISK_DEEPSEEK_O_PROJ_RECIPE:-hopper}" \
HYDRALISK_B12X_CLAMP_PATCH="${HYDRALISK_B12X_CLAMP_PATCH:-1}" \
HYDRALISK_B12X_CLAMP_LIMIT="${HYDRALISK_B12X_CLAMP_LIMIT:-10.0}" \
MAX_MODEL_LEN="${MAX_MODEL_LEN:-2048}" \
MAX_NUM_BATCHED_TOKENS="${MAX_NUM_BATCHED_TOKENS:-512}" \
GPU_MEMORY_UTILIZATION="${GPU_MEMORY_UTILIZATION:-0.95}" \
RUN_MODEL_SMOKE="${RUN_MODEL_SMOKE:-1}" \
"$SCRIPT_DIR/probe-deepseek-v4-b12x-g4-gce.sh"
